document.write("<h3>이건우의 자기소개</h3>");
document.write("<hr>");
document.write("<p>안녕하세요 저는 소프트웨어학과 2학년 이건우입니다.</p>");
document.write("<p>저는 웹 개발에 관심이 많으며 HTML, CSS, 그리고 JavaScript를 배우면서 다양한 실습을 진행해 왔습니다.</p>");
document.write("<br>");
document.write("<p>나를 소개합니다.</p>");
document.write("<ul>");
document.write("<li>저는 경성대학교에서 소프트웨어학과를 전공하며, 학업을 통해 C, 자바, HTML 등 다양한 프로그래밍 언어를 배우고 있습니다.</li>");
document.write("<li>저는 학습한 프로그래밍 언어를 실제 실습에 응용하고 문제를 해결하는 데 중점을 두고 있습니다.</li>");
document.write("<li>여가 시간에는 주로 컴퓨터 게임을 즐기며 스트레스를 해소합니다. 특히 FPS와 전략 게임을 좋아합니다.</li>");
document.write("</ul>");